package com.ego.pojo;

import java.io.Serializable;

public class GoodsAttrWithBLOBs extends GoodsAttr implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_attr.attr_value
     *
     * @mbg.generated Tue Apr 09 13:12:05 CST 2019
     */
    private String attrValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_attr.spec_value
     *
     * @mbg.generated Tue Apr 09 13:12:05 CST 2019
     */
    private String specValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods_attr
     *
     * @mbg.generated Tue Apr 09 13:12:05 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_attr.attr_value
     *
     * @return the value of t_goods_attr.attr_value
     *
     * @mbg.generated Tue Apr 09 13:12:05 CST 2019
     */
    public String getAttrValue() {
        return attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_attr.attr_value
     *
     * @param attrValue the value for t_goods_attr.attr_value
     *
     * @mbg.generated Tue Apr 09 13:12:05 CST 2019
     */
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue == null ? null : attrValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_attr.spec_value
     *
     * @return the value of t_goods_attr.spec_value
     *
     * @mbg.generated Tue Apr 09 13:12:05 CST 2019
     */
    public String getSpecValue() {
        return specValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_attr.spec_value
     *
     * @param specValue the value for t_goods_attr.spec_value
     *
     * @mbg.generated Tue Apr 09 13:12:05 CST 2019
     */
    public void setSpecValue(String specValue) {
        this.specValue = specValue == null ? null : specValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_attr
     *
     * @mbg.generated Tue Apr 09 13:12:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", attrValue=").append(attrValue);
        sb.append(", specValue=").append(specValue);
        sb.append("]");
        return sb.toString();
    }
}